### ISSUE TITLE
EmonCMS Error when viewing energy use report for the month of Aug

### ISSUE THREAD

**Issue by RaniaAlqass** [energylocal/cydynni#63]
User receives the "Mae eich adroddiad Ynni Lleol Bethesda ar gyfer Awst yn barod. | Your Bethesda Energy Local report for August is ready" email, but received an error message when clicking on the links.

![Screenshot_20190925-064208](https://user-images.githubusercontent.com/50102450/65623638-29d43a00-dfc0-11e9-8c93-5fccc7a1e0b9.png)

@TrystanLea

**Comment by TrystanLea** [comment]
Hello @RaniaAlqass this should now be fixed in the latest version of the dashboard
