### ISSUE TITLE
Brownie Hub: SP2 loses schedule when hub plugged back in.

### ISSUE THREAD

**Issue by ghost** [energylocal/cydynni#8]
Did a test to unplug Hub to simulate power loss at socket.
SP1 scheduled for later in the day.
SP2 following its schedule and ON (blue light).
EmonTH working.

Hub unplugged for 5 minutes. SP2 stayed on, then switched itself OFF
Plugged hub back in and showed presence of SP1, SP2, EmonTH and CydYnni in the BTHomehub device list and device list in dashboard scheduler.
Device at ip: (unknown) wanted to connect.
Clicked allow.
![image](https://user-images.githubusercontent.com/33721629/35337685-c1364074-0113-11e8-8e57-a8999f442001.png)

Device at ip: (unknown) wanted to connect.
Clicked Allow.
Logged out and in again.
emonTH still working.
SP1 schedule still there and plug OFF (as per schedule).
SP2 schedule disappeared and replaced with the following screen:

![c6](https://user-images.githubusercontent.com/33721629/35326898-fb59b21e-00ef-11e8-8973-5ffeb2987c8f.JPG)

SP1 rescheduled to see if it still works - yes it does.
Deleted SP2 from the dashboard. logged out and in again:
![c7](https://user-images.githubusercontent.com/33721629/35327268-18c88748-00f1-11e8-91c2-d99ea060273d.JPG)
**NOTE: what was SP1 is now SP2 and SP2 is now SP1 (!).**

Deleted all devices: SP1, SP2, emonTH.
emonTH appeared in the dashboard device list. SP1 and SP2 did not.
Unplugged SP1 and SP2 from power for 5 minutes.
Plugged in SP1 (correct green light sequence): SP1 appeared in device list as required after a couple of minutes.
Plugged in SP2 (correct green light sequence) : SP2 appeared in device list as required after a couple of minutes.
Both plugs working correctly with schedules.
Instructions are required exactly what to do if power goes off.

**Comment by TrystanLea** [comment]
Repeating here now after recent updates:

- SP1 scheduled for later in the day.
- SP2 following its schedule and ON (blue light).
- EmonTH working.

Hub unplugged for 5 minutes

- SP2 stayed on, did not switch off (expected)

Plugged hub back in and showed presence of SP1, SP2, EmonTH in device list in dashboard scheduler.
No message saying "Device at ip: (unknown) wanted to connect" - but I have seen this before.
There where however message saying Device at ip:192.168.1.71 etc - which should not show as these have already been approved.

Logged out and in again.
emonTH still working.
SP1 schedule still there and plug OFF (as per schedule).
*SP2 schedule disappeared and replaced with the following screen* - YES issue replicated
*SP1 rescheduled to see if it still works - yes it does* - YES confirmed
Deleted SP2 from the dashboard. logged out and in again:
*NOTE: what was SP1 is now SP2 and SP2 is now SP1* - I was not able to replicate this, SP2 stayed absent until I turned SP2 off and back on at the plug

Deleted all devices: SP1, SP2, emonTH.
emonTH appeared in the dashboard device list. SP1 and SP2 did not.
Unplugged SP1 and SP2 from power for 5 minutes.
Plugged in SP1 (correct green light sequence): SP1 appeared in device list as required after a couple of minutes.
Plugged in SP2 (correct green light sequence) : SP2 appeared in device list as required after a couple of minutes.
Both plugs working correctly with schedules. (YES confirmed)

I will investigate why SP2 disappears and work out how the plugs can automatically reappear if they are deleted from the interface without switching on/off at the wall.

**Comment by TrystanLea** [comment]
- fixed bug that resulted in the second smartplug scheduler disappearing after a reboot

**Comment by hiltoni** [comment]
OK thanks. I will test again under the same conditions on Friday 26/01/18 and see if I can reproduce the error that wasn't reproducible.

**Comment by hiltoni** [comment]
# Retest:
SP1 scheduled for later on:
![image](https://user-images.githubusercontent.com/33721629/35442878-ac7ece92-02a0-11e8-9b1c-2779d58808a3.png)

SP2 ON:

![image](https://user-images.githubusercontent.com/33721629/35443515-45afd3d4-02a3-11e8-871d-ebc1fbd22132.png)

Pulled plug on hub for 5 minutes:

SP1 stayed off, SP2 stayed on:
Plugged hub back in:
1) unable to immediately open SP1 or SP2 views on dashboard.
2) message appears 'device wants to connect:
![image](https://user-images.githubusercontent.com/33721629/35443052-870c88ba-02a1-11e8-8ea6-931f091c3b9c.png)
when you click allow, it pops up again. I clicked allow 5 times before I logged out of the dashboard.
We need an instruction to do this.
3) after logged in again on dashboard:
SP1 status = OFF - schedule correct as per diagram 1 above.
SP2 status = ON - schedule correct as per diagram 2 above.
4) SP2 switched off at the correct scheduled time of 14:30.

# TEST = PASS.

The user needs a prompt on dashboard to a)  tell them that their hub has lost power and b) that they must logout and login again.

**Comment by hiltoni** [comment]
Happy to close this one out if you are happy.

**Comment by hiltoni** [comment]
Related issue: SP2 finished its schedule and switched off at 14:30 (as said), however, on collapsing the view and looking at emonTH, then looking back at SP2:
![image](https://user-images.githubusercontent.com/33721629/35444710-47489e8e-02a7-11e8-99cb-23e0a0fbbf04.png)
# Where has the 3am - 3.30am come from?
I collapsed the view and reviewed SP1 and went back to SP2 view. SP2 remains as in the attached screenshot.

**Comment by hiltoni** [comment]
Further issue:
SP1 came on by itself (without a schedule) at 20:30. I went to dashboard and found the following screen for SP1:
![image](https://user-images.githubusercontent.com/33721629/35459873-d5a7ba8e-02d9-11e8-879a-8a16ce82f787.png).
Same view for SP2:
![image](https://user-images.githubusercontent.com/33721629/35459921-fc9a5142-02d9-11e8-8b59-82108573f41d.png).

I have no idea why this happened,

**Comment by TrystanLea** [comment]
Thanks @hiltoni I will look into it
