### ISSUE TITLE
logging in to the wrong dashboard

### ISSUE THREAD

**Issue by marygillie** [energylocal/cydynni#96]
I got the following from Nerina and when I log in as Admin it is the same, it takes you to Crickhowell rather than Machynlleth.

One more thing - the dashboard is now showing me the figures for Crickhowell, if I log out I can see the Machynlleth figures but as soon as I log in it changes back to Crickhowell. I assume this is just a temporary glitch but thought I’d let you know.
Regards,
Nerina

**Comment by TrystanLea** [comment]
Fixed, thanks
